apiVersion: v1
kind: Service
metadata:
  name: attestation-policy-gateway
  labels:
    app: attestation-policy-gateway
spec:
  selector:
    app: attestation-policy-gateway
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
